---
abstract: 'Apache Kafka low-level synchronous API, which does not use Zookeeper.'
author:
  - 'TrackingSoft LLC <sgladkov@trackingsoft.com>'
build_requires:
  Capture::Tiny: 0.22
  Config::IniFiles: 2.82
  Proc::Daemon: 0.14
  Sub::Install: 0.926
  Test::Deep: 0.109
  Test::Exception: 0.31
  Test::TCP: 2
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.74, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kafka
no_index:
  directory:
    - t
    - inc
requires:
  Const::Fast: 0.014
  Exception::Class: 1.37
  List::MoreUtils: 0.33
  Params::Util: 1.07
  Scalar::Util::Numeric: 0.22
  String::CRC32: 1.4
  Sys::SigAction: 0.15
  Try::Tiny: 0.18
  perl: 5.010
version: 0.800_4
